
export interface EmiCollection {
	accountId: number,
	accountName: string,
	partyDetailsId: number,
	party_ac_refId: number,
	partyContactNo1: string,
	partyContactNo2: string,
	partyEmailId: string,
	partyGstNo: string,
	partyBillingAddress: string,
	partyShipingAddress: string,
	partyOpeningBalance: number,
	partyAreaCode: string,
	partyDob: string,
	partyBloodGroup: string,
	partyAadharNo: string,
	partyPanNo: string,
	bookInfoId: number,
	bookInfoType_Ref: number,
	bookInfoFolio_Ref: number,
	bookInfoDate: string,
	emiId: number,
	emiNo: number,
	emiAmount: number,
	emiStatus: string,
	emiDate: string,
	emiMessage: string,
	emiSmsStatus: boolean,
	emi_BiId: number,

}
export interface EmiConfig {
	accountId: number,
	accountName: string,
	emiId: number,
	emiNo: number,
	emiAmount: number,
	emiStatus: string,
	emiDate: string,
	emiMessage: string,
	emiSmsStatus: boolean,
	emi_BiId: number
}
export interface ProductServiceConfig {
	accountId: number,
	accountName: string,
	psId: number,
	ps_Id: number,
	psEngineerName: string,
	psNo: number,
	psDate: string,
	psStatus: string,
	psMessage: string,
	psSmsStatus: string,
}