export interface EmployeeDetailsDTO {
    accountId: number,
    accountName: string,
    empDetailsId: number,
    emp_ac_refId: number,
    empContactNo1: string,
    empContactNo2: string,
    empEmailId: string,
    empGstNo: string,
    empBillingAddress: string,
    empShipingAddress: string,
    empOpeningBalance: string,
    empAreaCode: string,
    empDob: string,
    empBloodGroup: string,
    empJobeDesignation: string,
    empJoiningDate: string,
    empSalaryPackage: string,
    empAadharNo: string,
    empPanNo: string,
}
