
export interface InvoiceList {
  accountId: number,
  accountName: string,
  partyContactNo1: number,
  partyContactNo2: number,
  partyEmailId: string,
  partyGstNo: string,
  partyBillingAddress: string,
  partyShipingAddress: string,
  bookInfoId: number,
  bookInfoNarration: string,
  bookInfoDate: string,
  bookInfoType_Ref: number,
  bookInfoFolio_Ref: number,
  bookInfoUser_Ref: number,
  bookInfoAccount_Ref: number,
  invoiceNo: string,
  invoiceDate: string,
  ii_ilId: number,
  iiParticular: string,
  iiHsn: string,
  bookDetailsId: number,
  bookDetailsBookInfo_Ref: number,
  bookDetailsInventoryItems_Ref: number,
  bookDetailsParticularAmount: number,
  bookDetailsUnit: string,
  bookDetailsUnitValue: number,
  bookDetailsMolelNo: number,
  bookDetailsTradDiscount: number,
  bookDetailsTradDiscountAmount: number,
  bookDetailsCgst: number,
  bookDetailsSgst: number,
  bookDetailsIgst: number,
  bookDetailsCgstAmount: number,
  bookDetailsSgstAmount: number,
  bookDetailsIgstAmount: number
}